// ===== 이쯤 (Ijjeum) - 하드코딩 샘플 데이터 =====
// 스키마는 data.md 참고

export const MOOD_TAGS = ["조용한", "시끌벅적", "단체석", "회식", "데이트", "혼술", "루프탑", "감성"];

export const CUISINE_MENU_TAGS = {
  "한식": ["삼겹살", "곱창", "국밥", "찌개"],
  "양식": ["파스타", "스테이크", "피자"],
  "일식": ["스시", "이자카야", "라멘"],
  "중식": ["짜장/짬뽕", "마라", "딤섬"],
};

export const REGION_COORDS = {
  "을지로3가": { lat: 37.5662, lng: 126.9910 },
  "을지로": { lat: 37.5662, lng: 126.9910 },
  "공덕": { lat: 37.5443, lng: 126.9513 },
  "공덕역": { lat: 37.5443, lng: 126.9513 },
  "화곡": { lat: 37.5417, lng: 126.8409 },
  "성수": { lat: 37.5446, lng: 127.0559 },
  "강남역": { lat: 37.4979, lng: 127.0276 },
  "홍대입구": { lat: 37.5563, lng: 126.9236 },
  "신촌": { lat: 37.5559, lng: 126.9368 },
  "잠실": { lat: 37.5133, lng: 127.1000 },
  "건대입구": { lat: 37.5407, lng: 127.0693 },
};

export const CONCEPTS = [
  { value: "가볍게 한잔", icon: "Wine" },
  { value: "든든하게 식사", icon: "UtensilsCrossed" },
  { value: "술 없이 맛집 탐방", icon: "Soup" },
  { value: "대화 위주의 조용한 모임", icon: "MessageCircleHeart" },
  { value: "만취 목표", icon: "PartyPopper" },
  { value: "모르겠어요", icon: "HelpCircle" },
];

export const ROUNDS = ["1차", "2차", "3차 이상", "모르겠어요"];

export const PARTY_SIZES = ["1명", "2명", "3~4명", "5명 이상", "모르겠어요"];

export const CUISINE_TYPES = ["한식", "양식", "일식", "중식", "모르겠어요"];

// 샘플 식당 데이터 (16곳)
// 그룹1: 을지로3가 (한 지역 검색용, id 1~8)
// 그룹2: 공덕역 인근 (화곡 ↔ 성수 중간지점 검색용, id 9~16)
export const restaurants = [
  {
    id: 1,
    name: "골목집 포차",
    region: "을지로3가",
    lat: 37.5662,
    lng: 126.9910,
    moodTags: ["시끌벅적", "회식", "단체석"],
    cuisineType: "한식",
    menuTags: ["곱창", "찌개"],
    recommendedRound: ["1차", "2차"],
    rating: 4.4,
    reviewSummary: "왁자지껄한 분위기, 단체 회식으로 인기",
    phone: "02-1234-5678",
    menu: ["곱창전골", "제육볶음"],
    hours: "17:00 ~ 24:00",
  },
  {
    id: 2,
    name: "을지다방",
    region: "을지로3가",
    lat: 37.5665,
    lng: 126.9915,
    moodTags: ["조용한", "데이트", "감성"],
    cuisineType: "양식",
    menuTags: ["파스타"],
    recommendedRound: ["3차 이상"],
    rating: 4.6,
    reviewSummary: "레트로 감성 가득, 대화하기 좋아요",
    phone: "02-1234-5679",
    menu: ["크림파스타", "하우스와인"],
    hours: "18:00 ~ 01:00",
  },
  {
    id: 3,
    name: "을지로 국밥집",
    region: "을지로3가",
    lat: 37.5660,
    lng: 126.9905,
    moodTags: ["조용한"],
    cuisineType: "한식",
    menuTags: ["국밥"],
    recommendedRound: ["1차"],
    rating: 4.3,
    reviewSummary: "진한 국물, 든든한 한 끼로 딱이에요",
    phone: "02-1234-5680",
    menu: ["돼지국밥", "순대국"],
    hours: "24시간 영업",
  },
  {
    id: 4,
    name: "노가리집 을지로점",
    region: "을지로3가",
    lat: 37.5668,
    lng: 126.9920,
    moodTags: ["시끌벅적", "혼술"],
    cuisineType: "한식",
    menuTags: ["찌개"],
    recommendedRound: ["2차"],
    rating: 4.5,
    reviewSummary: "가볍게 한잔하기 좋은 노포 감성",
    phone: "02-1234-5681",
    menu: ["노가리", "계란말이"],
    hours: "17:00 ~ 01:00",
  },
  {
    id: 5,
    name: "스시야 을지로",
    region: "을지로3가",
    lat: 37.5655,
    lng: 126.9900,
    moodTags: ["데이트", "조용한"],
    cuisineType: "일식",
    menuTags: ["스시"],
    recommendedRound: ["1차"],
    rating: 4.7,
    reviewSummary: "신선한 스시로 분위기 있는 데이트 코스",
    phone: "02-1234-5682",
    menu: ["모듬스시", "사케"],
    hours: "17:30 ~ 22:30",
  },
  {
    id: 6,
    name: "마라황궁 을지로점",
    region: "을지로3가",
    lat: 37.5670,
    lng: 126.9895,
    moodTags: ["시끌벅적", "단체석", "회식"],
    cuisineType: "중식",
    menuTags: ["마라"],
    recommendedRound: ["1차", "2차"],
    rating: 4.2,
    reviewSummary: "매콤한 마라로 회식 인기 메뉴",
    phone: "02-1234-5683",
    menu: ["마라샹궈", "꿔바로우"],
    hours: "11:30 ~ 23:00",
  },
  {
    id: 7,
    name: "파스타공방 을지로",
    region: "을지로3가",
    lat: 37.5658,
    lng: 126.9918,
    moodTags: ["데이트", "조용한", "감성"],
    cuisineType: "양식",
    menuTags: ["파스타"],
    recommendedRound: ["1차"],
    rating: 4.5,
    reviewSummary: "아늑한 조명 아래 조용히 대화하기 좋아요",
    phone: "02-1234-5684",
    menu: ["알리오올리오", "리조또"],
    hours: "11:30 ~ 22:00",
  },
  {
    id: 8,
    name: "루프탑 비어 을지로",
    region: "을지로3가",
    lat: 37.5672,
    lng: 126.9908,
    moodTags: ["루프탑", "시끌벅적", "데이트"],
    cuisineType: "양식",
    menuTags: ["피자"],
    recommendedRound: ["2차", "3차 이상"],
    rating: 4.6,
    reviewSummary: "탁 트인 루프탑에서 맥주 한잔",
    phone: "02-1234-5685",
    menu: ["수제맥주", "화덕피자"],
    hours: "18:00 ~ 01:00",
  },
  {
    id: 9,
    name: "공덕찌개마을",
    region: "공덕",
    lat: 37.5443,
    lng: 126.9513,
    moodTags: ["조용한"],
    cuisineType: "한식",
    menuTags: ["찌개"],
    recommendedRound: ["1차"],
    rating: 4.3,
    reviewSummary: "집밥 같은 든든한 찌개 한 상",
    phone: "02-9876-0001",
    menu: ["김치찌개", "된장찌개"],
    hours: "10:00 ~ 21:00",
  },
  {
    id: 10,
    name: "공덕곱창골목",
    region: "공덕",
    lat: 37.5448,
    lng: 126.9520,
    moodTags: ["시끌벅적", "단체석", "회식"],
    cuisineType: "한식",
    menuTags: ["곱창"],
    recommendedRound: ["2차"],
    rating: 4.4,
    reviewSummary: "불맛 가득한 곱창으로 회식 만족도 최고",
    phone: "02-9876-0002",
    menu: ["곱창구이", "막창"],
    hours: "16:00 ~ 24:00",
  },
  {
    id: 11,
    name: "스테이크하우스 공덕",
    region: "공덕",
    lat: 37.5440,
    lng: 126.9508,
    moodTags: ["데이트", "조용한"],
    cuisineType: "양식",
    menuTags: ["스테이크"],
    recommendedRound: ["1차"],
    rating: 4.7,
    reviewSummary: "분위기 좋은 데이트 코스로 인기",
    phone: "02-9876-0003",
    menu: ["안심스테이크", "하우스와인"],
    hours: "11:30 ~ 22:00",
  },
  {
    id: 12,
    name: "이자카야 하나",
    region: "공덕",
    lat: 37.5450,
    lng: 126.9518,
    moodTags: ["혼술", "조용한"],
    cuisineType: "일식",
    menuTags: ["이자카야"],
    recommendedRound: ["2차"],
    rating: 4.5,
    reviewSummary: "혼자서도 편하게 한잔하기 좋아요",
    phone: "02-9876-0004",
    menu: ["사케", "꼬치구이"],
    hours: "18:00 ~ 01:00",
  },
  {
    id: 13,
    name: "딤섬가옥",
    region: "공덕",
    lat: 37.5445,
    lng: 126.9505,
    moodTags: ["데이트", "조용한", "감성"],
    cuisineType: "중식",
    menuTags: ["딤섬"],
    recommendedRound: ["1차"],
    rating: 4.6,
    reviewSummary: "고급스러운 분위기의 딤섬 코스",
    phone: "02-9876-0005",
    menu: ["샤오롱바오", "새우딤섬"],
    hours: "11:00 ~ 21:30",
  },
  {
    id: 14,
    name: "공덕포차",
    region: "공덕",
    lat: 37.5438,
    lng: 126.9515,
    moodTags: ["시끌벅적", "회식", "단체석"],
    cuisineType: "한식",
    menuTags: ["삼겹살"],
    recommendedRound: ["1차", "2차"],
    rating: 4.3,
    reviewSummary: "푸짐한 안주로 회식하기 좋아요",
    phone: "02-9876-0006",
    menu: ["삼겹살", "연탄불고기"],
    hours: "16:00 ~ 24:00",
  },
  {
    id: 15,
    name: "라멘텐 공덕",
    region: "공덕",
    lat: 37.5441,
    lng: 126.9525,
    moodTags: ["혼술", "조용한"],
    cuisineType: "일식",
    menuTags: ["라멘"],
    recommendedRound: ["1차"],
    rating: 4.4,
    reviewSummary: "진한 돈코츠 라멘 한 그릇",
    phone: "02-9876-0007",
    menu: ["돈코츠라멘", "교자"],
    hours: "11:00 ~ 22:00",
  },
  {
    id: 16,
    name: "감성바 공덕",
    region: "공덕",
    lat: 37.5446,
    lng: 126.9512,
    moodTags: ["감성", "조용한", "데이트"],
    cuisineType: "양식",
    menuTags: ["파스타"],
    recommendedRound: ["3차 이상"],
    rating: 4.7,
    reviewSummary: "조명이 예쁜 감성 위스키 바",
    phone: "02-9876-0008",
    menu: ["하이볼", "안주플레이트"],
    hours: "19:00 ~ 02:00",
  },
];

// 커뮤니티 탭 - 모임 후기 게시판 (하드코딩 샘플)
export const COMMUNITY_POSTS = [
  {
    id: 1,
    author: "민지",
    restaurantId: 1,
    round: "2차",
    partySize: "5명 이상",
    text: "팀 회식 2차로 다녀왔는데 다들 만족했어요! 곱창전골이 특히 인기 만점이었습니다. 시끌벅적한 분위기라 단체 모임엔 딱이에요.",
    likes: 24,
    comments: 6,
    createdAt: "3일 전",
  },
  {
    id: 2,
    author: "현우",
    restaurantId: 5,
    round: "1차",
    partySize: "2명",
    text: "여자친구랑 기념일에 갔는데 스시가 정말 신선했어요. 조용해서 대화하기도 좋고, 데이트 코스로 강추합니다.",
    likes: 41,
    comments: 9,
    createdAt: "5일 전",
  },
  {
    id: 3,
    author: "소연",
    restaurantId: 12,
    round: "2차",
    partySize: "1명",
    text: "퇴근하고 혼자 한잔하러 갔는데 사장님이 친절하시고 부담 없어서 좋았어요. 혼술하기 딱 좋은 곳!",
    likes: 18,
    comments: 3,
    createdAt: "1주 전",
  },
  {
    id: 4,
    author: "지훈",
    restaurantId: 8,
    round: "3차 이상",
    partySize: "3~4명",
    text: "친구들이랑 3차로 루프탑 왔는데 뷰가 미쳤습니다... 수제맥주랑 화덕피자 조합 최고예요.",
    likes: 57,
    comments: 12,
    createdAt: "1주 전",
  },
  {
    id: 5,
    author: "예린",
    restaurantId: 16,
    round: "3차 이상",
    partySize: "2명",
    text: "조명이 너무 예뻐서 사진 찍기 좋고, 하이볼도 맛있어요. 조용히 대화하면서 마무리하기 좋은 3차 장소.",
    likes: 33,
    comments: 5,
    createdAt: "2주 전",
  },
  {
    id: 6,
    author: "동현",
    restaurantId: 10,
    round: "2차",
    partySize: "5명 이상",
    text: "부서 회식으로 곱창골목 다녀왔어요. 불맛 제대로고 양도 푸짐해서 다 같이 배부르게 먹었습니다.",
    likes: 21,
    comments: 4,
    createdAt: "2주 전",
  },
  {
    id: 7,
    author: "다은",
    restaurantId: 13,
    round: "1차",
    partySize: "2명",
    text: "딤섬 코스가 고급스러워서 특별한 날 데이트로 다녀왔어요. 샤오롱바오 육즙 대박입니다.",
    likes: 29,
    comments: 7,
    createdAt: "3주 전",
  },
  {
    id: 8,
    author: "재현",
    restaurantId: 4,
    round: "2차",
    partySize: "3~4명",
    text: "노포 감성 제대로예요. 노가리에 맥주 한잔 딱이고, 가볍게 한잔하기 좋은 2차 장소로 추천합니다.",
    likes: 15,
    comments: 2,
    createdAt: "3주 전",
  },
];
